import { prisma } from "../config/seeds.js";

export const outboxMessageDB = prisma.outboxMessage as typeof prisma.outboxMessage & { seeds?: () => Promise<void> };
export const inboxMessageDB = prisma.inboxMessage as typeof prisma.inboxMessage & { seeds?: () => Promise<void> };
export const eventDB = prisma.event as typeof prisma.event & { seeds?: () => Promise<void> };
export const userDB = prisma.user as typeof prisma.user & { seeds?: () => Promise<void> };
export const vendorDB = prisma.vendor as typeof prisma.vendor & { seeds?: () => Promise<void> };
export const rawMaterialDB = prisma.rawMaterial as typeof prisma.rawMaterial & { seeds?: () => Promise<void> };
export const rMPurchasingDB = prisma.rMPurchasing as typeof prisma.rMPurchasing & { seeds?: () => Promise<void> };
export const purchaseDataDB = prisma.purchaseData as typeof prisma.purchaseData & { seeds?: () => Promise<void> };
export const productionDB = prisma.production as typeof prisma.production & { seeds?: () => Promise<void> };
export const laneDB = prisma.lane as typeof prisma.lane & { seeds?: () => Promise<void> };
export const chamberDB = prisma.chamber as typeof prisma.chamber & { seeds?: () => Promise<void> };
export const chamberStockDB = prisma.chamberStock as typeof prisma.chamberStock & { seeds?: () => Promise<void> };
export const packetDB = prisma.packet as typeof prisma.packet & { seeds?: () => Promise<void> };
export const productDB = prisma.product as typeof prisma.product & { seeds?: () => Promise<void> };
export const packagingDB = prisma.packaging as typeof prisma.packaging & { seeds?: () => Promise<void> };
export const dispatchOrderDB = prisma.dispatchOrder as typeof prisma.dispatchOrder & { seeds?: () => Promise<void> };
export const orderProductDB = prisma.orderProduct as typeof prisma.orderProduct & { seeds?: () => Promise<void> };
export const truckDetailDB = prisma.truckDetail as typeof prisma.truckDetail & { seeds?: () => Promise<void> };
export const challanDB = prisma.challan as typeof prisma.challan & { seeds?: () => Promise<void> };
export const imageDB = prisma.image as typeof prisma.image & { seeds?: () => Promise<void> };
export const stockMovementDB = prisma.stockMovement as typeof prisma.stockMovement & { seeds?: () => Promise<void> };
